Implement musun input generator
legend-exp/remage pull request #26
Opened 2022-12-15 11:04 UTC by MoritzNeuberger

Overview:
- Added class to generate muons using a MUSUN file input
- Added class to read a MUSUN file (singleton) 
- Added example to experiment with the new generator based on 02-HPGe
- Added an example MUSUN input file with 10000 muons (MUSUN_10k_events.dat)

2023-01-11 10:27 UTC, gipert commented on include/RMGReaderMUSUN.hh
> +class RMGReaderMUSUN {
Can you investigate if a MUSUN file can be interpreted as CSV, so we can use `G4CsvAnalysisReader` to parse it (see `RMGVertexFromFile`)?

2023-07-05 10:02 UTC, gipert commented
What is the status here? Only need to better handle the header as we discussed?

2024-05-02 11:54 UTC, ManuelHu requested changes
This file should be deleted (also locally,

2024-05-02 11:54 UTC, ManuelHu commented on include/ProjectInfo.hh
> +// other useful GEANT4 exported variables:
This file should be removed, it has been replaced by the (git-excluded) `RMGConfig.hh`

2024-05-02 11:54 UTC, ManuelHu commented on include/RMGGeneratorMUSUNCosmicMuons.hh
> +#include "ProjectInfo.hh"
`RMGConfig.hh`

2024-05-02 13:10 UTC, ManuelHu commented
Now there are some parts of recent `main` branch changes duplicated in this PR... (and `ProjectInfo.hh` is still there, which is the cause for the slim build failures...) Maybe a rebase on the latest main would help :-)

2024-05-02 13:13 UTC, ManuelHu requested changes

2024-05-02 13:51 UTC, MoritzNeuberger commented
So, a problem with the multithreaded implementation. G4CsvAnalysisReader expects a separate file for each thread. Specifically, it expects them in this format: `FILENAME_nt_MUSUN_t0.csv, FILENAME_nt_MUSUN_t1.csv, ...` where tX is the iterable. Since we already control the input file in the copy step, I guess you could get around this by splitting the initial file into `nThreads` number of sub-files that we feed into the threads.

2024-05-02 14:51 UTC, MoritzNeuberger commented
So, there is a problem with the multithreaded implementation. The G4CsvAnalysisReader instance is currently initialized in the `BeginRunAction` of the generator class, so each thread will spawn a separate instance, meaning that each thread will go through all entries in the input file. Could we instead initialize it in the user action?

2024-05-02 15:07 UTC, MoritzNeuberger commented
At this point, I am considering testing whether a Singelton with some mutex might be the way to go.

2024-05-02 15:49 UTC, MoritzNeuberger commented
As this point I am thinking of working with a singelton and mutex similar to [this](https://github.com/Geant4/geant4/blob/master/examples/extended/runAndEvent/RE05/src/RE05PrimaryGeneratorAction.cc) Geant4 example.

2024-05-03 09:44 UTC, MoritzNeuberger commented
In the example I now get this seg violation:

```
 *** Break *** segmentation violation
WARNING - Attempt to delete the physical volume store while geometry closed !
WARNING - Attempt to delete the logical volume store while geometry closed !
WARNING - Attempt to delete the solid store while geometry closed !
WARNING - Attempt to delete the region store while geometry closed !
```

I guess I messed up somewhere.

2024-05-03 14:42 UTC, MoritzNeuberger commented
Seems to not throw the seg violation anymore. It was probably related to an automatic delete of the `G4CsvAnalysisReader` at the end of the program, making the manual delete unnecessary?

Anyway, I think the pull request is not feature-complete. What do you guys think?

2024-05-06 12:59 UTC, ManuelHu requested changes
Some macro commands will not work on current main

2024-05-06 12:59 UTC, ManuelHu commented on examples/05-MUSUN/run.mac
> +# /RMG/Manager/Logging/LogLevelScreen debug
```suggestion
# /RMG/Manager/Logging/LogLevel debug
```

2024-05-06 12:59 UTC, ManuelHu commented on examples/05-MUSUN/vis-traj.mac
> +/RMG/Manager/Logging/LogLevelScreen debug
```suggestion
/RMG/Manager/Logging/LogLevel debug
```

2024-05-06 12:59 UTC, ManuelHu commented on src/RMGGeneratorMUSUNCosmicMuons.cc
> +#include "math.h"
```suggestion
#include <filesystem>
#include <math>
#include <vector>
```

2024-05-06 12:59 UTC, ManuelHu commented on src/RMGGeneratorMUSUNCosmicMuons.cc
> +
```suggestion
#include "RMGVGenerator.hh"

```

2024-05-06 12:59 UTC, ManuelHu commented on src/RMGGeneratorMUSUNCosmicMuons.cc
> +
```suggestion
```

2024-05-06 13:25 UTC, ManuelHu requested changes

2024-05-06 13:25 UTC, ManuelHu commented on src/RMGGeneratorMUSUNCosmicMuons.cc
> +#include <math>
```suggestion
#include <cmath>
```

2024-05-06 13:32 UTC, ManuelHu approved these changes

2024-05-06 13:32 UTC, ManuelHu commented on include/RMGGeneratorMUSUNCosmicMuons.hh
> +    virtual void SetParticlePosition(G4ThreeVector vec) override {};
```suggestion
    virtual void SetParticlePosition(G4ThreeVector) override {};
```

2024-05-06 13:37 UTC, merged